import requests

API_URL = "http://localhost:8000/generate-banner"

form_data = {
    "image_url": "https://wallpapercave.com/wp/wp3788129.jpg",  # Replace if needed
    "text": "This banner was generated by testing the FastAPI form-based endpoint.",
    "footer": "@newsmedia"
}

response = requests.post(API_URL, data=form_data)

if response.status_code == 200:
    result = response.json()
    print("✅ Public image URL:")
    print(result["image_url"])
else:
    print(f"❌ Error: {response.status_code}")
    print(response.text)

# Input for testing
# payload = {
#     "bg": "https://wallpapercave.com/wp/wp3788129.jpg",
#     "text": "The article reviews various e-readers, highlighting the Kindle Paperwhite as the best choice for most due to its display and Amazon integration. Kobo's Libra Colour offers a non-Amazon alternative with stylus support. E-readers are compared on features like display quality, ecosystem, and price.",
#     "footer": "@newsmedia"
# }

